import type { components } from "./generated/schema";

export type Health = components["schemas"]["Health"];
export type Node = components["schemas"]["Node"];
export type ErrorResponse = components["schemas"]["ErrorResponse"];
export type RuntimeDiscovery = components["schemas"]["RuntimeDiscovery"];
export type RuntimeDiscoveryState = components["schemas"]["RuntimeDiscoveryState"];
export type RuntimeCandidate = components["schemas"]["RuntimeCandidate"];
export type Operation = components["schemas"]["Operation"];
export type OperationList = components["schemas"]["OperationList"];
export type Instance = components["schemas"]["Instance"];
export type InstanceList = components["schemas"]["InstanceList"];
export type Lifecycle = components["schemas"]["Lifecycle"];
export type ManagementHealthFinding = components["schemas"]["ManagementHealthFinding"];
export type ManagementHealth = components["schemas"]["ManagementHealth"];
export type ManagementLogEntry = components["schemas"]["ManagementLogEntry"];
export type ManagementLogSnapshot = components["schemas"]["ManagementLogSnapshot"];
export type ManagementLogCategory = ManagementLogSnapshot["category"];
export type Skill = components["schemas"]["Skill"];
export type SkillList = components["schemas"]["SkillList"];
export type SkillSource = components["schemas"]["SkillSource"];
export type SkillSourceList = components["schemas"]["SkillSourceList"];
export type MCPServer = components["schemas"]["MCPServer"];
export type MCPServerList = components["schemas"]["MCPServerList"];
export type MCPPreset = components["schemas"]["MCPPreset"];
export type MCPPresetList = components["schemas"]["MCPPresetList"];
export type ManagementUpgradePlan = components["schemas"]["ManagementUpgradePlan"];
export type ManagementUpgradeCandidate = components["schemas"]["ManagementUpgradeCandidate"];
export type ManagementBackup = components["schemas"]["ManagementBackup"];
export type ManagementBackupList = components["schemas"]["ManagementBackupList"];
export type Channel = components["schemas"]["Channel"];
export type ChannelList = components["schemas"]["ChannelList"];
export type ChannelQr = components["schemas"]["ChannelQr"];
export type ChannelPairingStatus = components["schemas"]["ChannelPairingStatus"];
export type ChannelPairingApproval = components["schemas"]["ChannelPairingApproval"];
export type ModelProviderPreset = components["schemas"]["ModelProviderPreset"];
export type ModelProviderPresetList = components["schemas"]["ModelProviderPresetList"];
export type ModelConfiguration = components["schemas"]["ModelConfiguration"];
export type ModelCredential = components["schemas"]["ModelCredential"];
export type ModelProviderCatalog = components["schemas"]["ModelProviderCatalog"];
export type ModelProviderConnection = components["schemas"]["ModelProviderConnection"];
export type ModelProviderConnectionList = components["schemas"]["ModelProviderConnectionList"];
export type ModelProfile = components["schemas"]["ModelProfile"];
export type ModelProfileList = components["schemas"]["ModelProfileList"];
export type RuntimeModelDefault = components["schemas"]["RuntimeModelDefault"];
export type InstanceModelBinding = components["schemas"]["InstanceModelBinding"];
export type InstanceModelBindingList = components["schemas"]["InstanceModelBindingList"];
export type HermesDownloadSources = components["schemas"]["HermesDownloadSources"];
export type HermesPrerequisites = {
  node: { state: string; version: string; errorCode: string | null; retryable: boolean };
  npm: { state: string; version: string; errorCode: string | null; retryable: boolean };
  nodeDependencies: { state: string; version: string; errorCode: string | null; retryable: boolean };
  checkedAt: string;
  activeOperationId: string | null;
};

export type DaemonSession = {
  baseUrl: string;
  token: string;
  protocolVersion: string;
};
